module SurgeAPI
  class Account = SurgeAPI::Models::Account

  class AccountArchiveParams = SurgeAPI::Models::AccountArchiveParams

  class AccountCreateParams = SurgeAPI::Models::AccountCreateParams

  class AccountRetrieveStatusParams = SurgeAPI::Models::AccountRetrieveStatusParams

  class AccountStatus = SurgeAPI::Models::AccountStatus

  class AccountUpdateParams = SurgeAPI::Models::AccountUpdateParams

  class Blast = SurgeAPI::Models::Blast

  class BlastCreateParams = SurgeAPI::Models::BlastCreateParams

  class CallEndedWebhookEvent = SurgeAPI::Models::CallEndedWebhookEvent

  class Campaign = SurgeAPI::Models::Campaign

  class CampaignApprovedWebhookEvent = SurgeAPI::Models::CampaignApprovedWebhookEvent

  class CampaignCreateParams = SurgeAPI::Models::CampaignCreateParams

  module CampaignParams = SurgeAPI::Models::CampaignParams

  class CampaignRetrieveParams = SurgeAPI::Models::CampaignRetrieveParams

  class Contact = SurgeAPI::Models::Contact

  class ContactCreateParams = SurgeAPI::Models::ContactCreateParams

  class ContactListParams = SurgeAPI::Models::ContactListParams

  class ContactOptedInWebhookEvent = SurgeAPI::Models::ContactOptedInWebhookEvent

  class ContactOptedOutWebhookEvent = SurgeAPI::Models::ContactOptedOutWebhookEvent

  class ContactRetrieveParams = SurgeAPI::Models::ContactRetrieveParams

  class ContactUpdateParams = SurgeAPI::Models::ContactUpdateParams

  class ConversationCreatedWebhookEvent = SurgeAPI::Models::ConversationCreatedWebhookEvent

  class Error = SurgeAPI::Models::Error

  class LinkFollowedWebhookEvent = SurgeAPI::Models::LinkFollowedWebhookEvent

  class Message = SurgeAPI::Models::Message

  class MessageCreateParams = SurgeAPI::Models::MessageCreateParams

  class MessageDeliveredWebhookEvent = SurgeAPI::Models::MessageDeliveredWebhookEvent

  class MessageFailedWebhookEvent = SurgeAPI::Models::MessageFailedWebhookEvent

  class MessageListParams = SurgeAPI::Models::MessageListParams

  module MessageParams = SurgeAPI::Models::MessageParams

  class MessageReceivedWebhookEvent = SurgeAPI::Models::MessageReceivedWebhookEvent

  class MessageRetrieveParams = SurgeAPI::Models::MessageRetrieveParams

  class MessageSentWebhookEvent = SurgeAPI::Models::MessageSentWebhookEvent

  class Organization = SurgeAPI::Models::Organization

  class PhoneNumber = SurgeAPI::Models::PhoneNumber

  class PhoneNumberListParams = SurgeAPI::Models::PhoneNumberListParams

  class PhoneNumberPurchaseParams = SurgeAPI::Models::PhoneNumberPurchaseParams

  class RecordingGetFileParams = SurgeAPI::Models::RecordingGetFileParams

  module UnwrapWebhookEvent = SurgeAPI::Models::UnwrapWebhookEvent

  class User = SurgeAPI::Models::User

  class UserCreateParams = SurgeAPI::Models::UserCreateParams

  class UserCreateTokenParams = SurgeAPI::Models::UserCreateTokenParams

  class UserDeleteParams = SurgeAPI::Models::UserDeleteParams

  class UserRetrieveParams = SurgeAPI::Models::UserRetrieveParams

  class UserTokenResponse = SurgeAPI::Models::UserTokenResponse

  class UserUpdateParams = SurgeAPI::Models::UserUpdateParams

  class Verification = SurgeAPI::Models::Verification

  class VerificationCheck = SurgeAPI::Models::VerificationCheck

  class VerificationCheckParams = SurgeAPI::Models::VerificationCheckParams

  class VerificationCreateParams = SurgeAPI::Models::VerificationCreateParams

  class VoicemailReceivedWebhookEvent = SurgeAPI::Models::VoicemailReceivedWebhookEvent

  class WebhookUnwrapParams = SurgeAPI::Models::WebhookUnwrapParams
end
