module Surge
  module Resources
    class Accounts
      def create: (
        name: String,
        ?brand_name: String?,
        ?organization: Surge::OrganizationParams,
        ?time_zone: String,
        ?request_options: Surge::request_opts
      ) -> Surge::Account

      def update: (
        String id,
        ?brand_name: String,
        ?name: String,
        ?organization: Surge::OrganizationParams,
        ?time_zone: String?,
        ?request_options: Surge::request_opts
      ) -> Surge::Account

      def retrieve_status: (
        String account_id,
        ?capabilities: ::Array[Surge::Models::AccountRetrieveStatusParams::capability],
        ?request_options: Surge::request_opts
      ) -> Surge::AccountStatus

      def initialize: (client: Surge::Client) -> void
    end
  end
end
