module Surge
  module Resources
    class Campaigns
      def create: (
        String account_id,
        consent_flow: String,
        description: String,
        message_samples: ::Array[String],
        privacy_policy_url: String,
        use_cases: ::Array[Surge::Models::CampaignParams::use_case],
        volume: Surge::Models::CampaignParams::volume,
        ?includes: ::Array[Surge::Models::CampaignParams::include_],
        ?link_sample: String,
        ?terms_and_conditions_url: String,
        ?request_options: Surge::request_opts
      ) -> Surge::Campaign

      def initialize: (client: Surge::Client) -> void
    end
  end
end
