module Surge
  module Resources
    class PhoneNumbers
      def purchase: (
        String account_id,
        ?area_code: String,
        ?latitude: Float,
        ?longitude: Float,
        ?type: Surge::Models::PhoneNumberPurchaseParams::type_,
        ?request_options: Surge::request_opts
      ) -> Surge::PhoneNumber

      def initialize: (client: Surge::Client) -> void
    end
  end
end
