module Surge
  module Resources
    class Verifications
      def create: (
        phone_number: String,
        ?request_options: Surge::request_opts
      ) -> Surge::Verification

      def check: (
        String id,
        code: String,
        ?request_options: Surge::request_opts
      ) -> Surge::VerificationCheck

      def initialize: (client: Surge::Client) -> void
    end
  end
end
