module Surge
  class Account = Surge::Models::Account

  class AccountCreateParams = Surge::Models::AccountCreateParams

  class AccountParams = Surge::Models::AccountParams

  class AccountRetrieveStatusParams = Surge::Models::AccountRetrieveStatusParams

  class AccountStatus = Surge::Models::AccountStatus

  class AccountUpdateParams = Surge::Models::AccountUpdateParams

  class AttachmentParams = Surge::Models::AttachmentParams

  class Blast = Surge::Models::Blast

  class BlastCreateParams = Surge::Models::BlastCreateParams

  class BlastParams = Surge::Models::BlastParams

  class CallEndedWebhookEvent = Surge::Models::CallEndedWebhookEvent

  class Campaign = Surge::Models::Campaign

  class CampaignApprovedWebhookEvent = Surge::Models::CampaignApprovedWebhookEvent

  class CampaignCreateParams = Surge::Models::CampaignCreateParams

  class CampaignParams = Surge::Models::CampaignParams

  class Contact = Surge::Models::Contact

  class ContactCreateParams = Surge::Models::ContactCreateParams

  class ContactParams = Surge::Models::ContactParams

  class ContactRetrieveParams = Surge::Models::ContactRetrieveParams

  class ContactUpdateParams = Surge::Models::ContactUpdateParams

  class ConversationCreatedWebhookEvent = Surge::Models::ConversationCreatedWebhookEvent

  class Error = Surge::Models::Error

  class Message = Surge::Models::Message

  class MessageCreateParams = Surge::Models::MessageCreateParams

  class MessageDeliveredWebhookEvent = Surge::Models::MessageDeliveredWebhookEvent

  class MessageFailedWebhookEvent = Surge::Models::MessageFailedWebhookEvent

  module MessageParams = Surge::Models::MessageParams

  class MessageReceivedWebhookEvent = Surge::Models::MessageReceivedWebhookEvent

  class MessageSentWebhookEvent = Surge::Models::MessageSentWebhookEvent

  class Organization = Surge::Models::Organization

  class OrganizationParams = Surge::Models::OrganizationParams

  class PhoneNumber = Surge::Models::PhoneNumber

  class PhoneNumberPurchaseParams = Surge::Models::PhoneNumberPurchaseParams

  module UnwrapWebhookEvent = Surge::Models::UnwrapWebhookEvent

  class User = Surge::Models::User

  class UserCreateParams = Surge::Models::UserCreateParams

  class UserCreateTokenParams = Surge::Models::UserCreateTokenParams

  class UserParams = Surge::Models::UserParams

  class UserRetrieveParams = Surge::Models::UserRetrieveParams

  class UserTokenParams = Surge::Models::UserTokenParams

  class UserTokenResponse = Surge::Models::UserTokenResponse

  class UserUpdateParams = Surge::Models::UserUpdateParams

  class Verification = Surge::Models::Verification

  class VerificationCheck = Surge::Models::VerificationCheck

  class VerificationCheckParams = Surge::Models::VerificationCheckParams

  class VerificationCreateParams = Surge::Models::VerificationCreateParams

  class VerificationParams = Surge::Models::VerificationParams

  class WebhookUnwrapParams = Surge::Models::WebhookUnwrapParams
end
