# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "surge_api/version"
require_relative "surge_api/internal/util"
require_relative "surge_api/internal/type/converter"
require_relative "surge_api/internal/type/unknown"
require_relative "surge_api/internal/type/boolean"
require_relative "surge_api/internal/type/file_input"
require_relative "surge_api/internal/type/enum"
require_relative "surge_api/internal/type/union"
require_relative "surge_api/internal/type/array_of"
require_relative "surge_api/internal/type/hash_of"
require_relative "surge_api/internal/type/base_model"
require_relative "surge_api/internal/type/base_page"
require_relative "surge_api/internal/type/request_parameters"
require_relative "surge_api/internal"
require_relative "surge_api/request_options"
require_relative "surge_api/file_part"
require_relative "surge_api/errors"
require_relative "surge_api/internal/transport/base_client"
require_relative "surge_api/internal/transport/pooled_net_requester"
require_relative "surge_api/client"
require_relative "surge_api/models/campaign_params"
require_relative "surge_api/models/message_params"
require_relative "surge_api/models/account"
require_relative "surge_api/models/account_archive_params"
require_relative "surge_api/models/account_create_params"
require_relative "surge_api/models/account_retrieve_status_params"
require_relative "surge_api/models/account_status"
require_relative "surge_api/models/account_update_params"
require_relative "surge_api/models/blast"
require_relative "surge_api/models/blast_create_params"
require_relative "surge_api/models/call_ended_webhook_event"
require_relative "surge_api/models/campaign"
require_relative "surge_api/models/campaign_approved_webhook_event"
require_relative "surge_api/models/campaign_create_params"
require_relative "surge_api/models/contact"
require_relative "surge_api/models/contact_create_params"
require_relative "surge_api/models/contact_opted_in_webhook_event"
require_relative "surge_api/models/contact_opted_out_webhook_event"
require_relative "surge_api/models/contact_retrieve_params"
require_relative "surge_api/models/contact_update_params"
require_relative "surge_api/models/conversation_created_webhook_event"
require_relative "surge_api/models/error"
require_relative "surge_api/models/link_followed_webhook_event"
require_relative "surge_api/models/message"
require_relative "surge_api/models/message_create_params"
require_relative "surge_api/models/message_delivered_webhook_event"
require_relative "surge_api/models/message_failed_webhook_event"
require_relative "surge_api/models/message_received_webhook_event"
require_relative "surge_api/models/message_retrieve_params"
require_relative "surge_api/models/message_sent_webhook_event"
require_relative "surge_api/models/organization"
require_relative "surge_api/models/phone_number"
require_relative "surge_api/models/phone_number_list_params"
require_relative "surge_api/models/phone_number_list_response"
require_relative "surge_api/models/phone_number_purchase_params"
require_relative "surge_api/models/unwrap_webhook_event"
require_relative "surge_api/models/user"
require_relative "surge_api/models/user_create_params"
require_relative "surge_api/models/user_create_token_params"
require_relative "surge_api/models/user_delete_params"
require_relative "surge_api/models/user_retrieve_params"
require_relative "surge_api/models/user_token_response"
require_relative "surge_api/models/user_update_params"
require_relative "surge_api/models/verification"
require_relative "surge_api/models/verification_check"
require_relative "surge_api/models/verification_check_params"
require_relative "surge_api/models/verification_create_params"
require_relative "surge_api/models/webhook_unwrap_params"
require_relative "surge_api/models"
require_relative "surge_api/resources/accounts"
require_relative "surge_api/resources/blasts"
require_relative "surge_api/resources/campaigns"
require_relative "surge_api/resources/contacts"
require_relative "surge_api/resources/messages"
require_relative "surge_api/resources/phone_numbers"
require_relative "surge_api/resources/users"
require_relative "surge_api/resources/verifications"
require_relative "surge_api/resources/webhooks"
