module Surge
  module Models
    type campaign_params =
      {
        consent_flow: String,
        description: String,
        message_samples: ::Array[String],
        privacy_policy_url: String,
        use_cases: ::Array[Surge::Models::CampaignParams::use_case],
        volume: Surge::Models::CampaignParams::volume,
        includes: ::Array[Surge::Models::CampaignParams::include_],
        link_sample: String,
        terms_and_conditions_url: String
      }

    class CampaignParams < Surge::Internal::Type::BaseModel
      attr_accessor consent_flow: String

      attr_accessor description: String

      attr_accessor message_samples: ::Array[String]

      attr_accessor privacy_policy_url: String

      attr_accessor use_cases: ::Array[Surge::Models::CampaignParams::use_case]

      attr_accessor volume: Surge::Models::CampaignParams::volume

      attr_reader includes: ::Array[Surge::Models::CampaignParams::include_]?

      def includes=: (
        ::Array[Surge::Models::CampaignParams::include_]
      ) -> ::Array[Surge::Models::CampaignParams::include_]

      attr_reader link_sample: String?

      def link_sample=: (String) -> String

      attr_reader terms_and_conditions_url: String?

      def terms_and_conditions_url=: (String) -> String

      def initialize: (
        consent_flow: String,
        description: String,
        message_samples: ::Array[String],
        privacy_policy_url: String,
        use_cases: ::Array[Surge::Models::CampaignParams::use_case],
        volume: Surge::Models::CampaignParams::volume,
        ?includes: ::Array[Surge::Models::CampaignParams::include_],
        ?link_sample: String,
        ?terms_and_conditions_url: String
      ) -> void

      def to_hash: -> {
        consent_flow: String,
        description: String,
        message_samples: ::Array[String],
        privacy_policy_url: String,
        use_cases: ::Array[Surge::Models::CampaignParams::use_case],
        volume: Surge::Models::CampaignParams::volume,
        includes: ::Array[Surge::Models::CampaignParams::include_],
        link_sample: String,
        terms_and_conditions_url: String
      }

      type use_case =
        :account_notification
        | :customer_care
        | :delivery_notification
        | :fraud_alert
        | :higher_education
        | :marketing
        | :polling_voting
        | :public_service_announcement
        | :security_alert
        | :two_factor_authentication

      module UseCase
        extend Surge::Internal::Type::Enum

        ACCOUNT_NOTIFICATION: :account_notification
        CUSTOMER_CARE: :customer_care
        DELIVERY_NOTIFICATION: :delivery_notification
        FRAUD_ALERT: :fraud_alert
        HIGHER_EDUCATION: :higher_education
        MARKETING: :marketing
        POLLING_VOTING: :polling_voting
        PUBLIC_SERVICE_ANNOUNCEMENT: :public_service_announcement
        SECURITY_ALERT: :security_alert
        TWO_FACTOR_AUTHENTICATION: :two_factor_authentication

        def self?.values: -> ::Array[Surge::Models::CampaignParams::use_case]
      end

      type volume = :high | :low

      module Volume
        extend Surge::Internal::Type::Enum

        HIGH: :high
        LOW: :low

        def self?.values: -> ::Array[Surge::Models::CampaignParams::volume]
      end

      type include_ = :links | :phone_numbers | :age_gated | :direct_lending

      module Include
        extend Surge::Internal::Type::Enum

        LINKS: :links
        PHONE_NUMBERS: :phone_numbers
        AGE_GATED: :age_gated
        DIRECT_LENDING: :direct_lending

        def self?.values: -> ::Array[Surge::Models::CampaignParams::include_]
      end
    end
  end
end
