module Surge
  module Models
    type message_create_params =
      { message_params: Surge::Models::message_params }
      & Surge::Internal::Type::request_parameters

    class MessageCreateParams < Surge::Internal::Type::BaseModel
      extend Surge::Internal::Type::RequestParameters::Converter
      include Surge::Internal::Type::RequestParameters

      def message_params: -> Surge::Models::message_params

      def message_params=: (
        Surge::Models::message_params _
      ) -> Surge::Models::message_params

      def initialize: (
        message_params: Surge::Models::message_params,
        ?request_options: Surge::request_opts
      ) -> void

      def to_hash: -> {
        message_params: Surge::Models::message_params,
        request_options: Surge::RequestOptions
      }
    end
  end
end
