module Surge
  module Models
    type unwrap_webhook_event =
      Surge::CallEndedWebhookEvent
      | Surge::CampaignApprovedWebhookEvent
      | Surge::ConversationCreatedWebhookEvent
      | Surge::MessageDeliveredWebhookEvent
      | Surge::MessageFailedWebhookEvent
      | Surge::MessageReceivedWebhookEvent
      | Surge::MessageSentWebhookEvent

    module UnwrapWebhookEvent
      extend Surge::Internal::Type::Union

      def self?.variants: -> ::Array[Surge::Models::unwrap_webhook_event]
    end
  end
end
