module Surge
  module Models
    type user_create_params = {  } & Surge::Internal::Type::request_parameters

    class UserCreateParams < Surge::Models::UserParams
      extend Surge::Internal::Type::RequestParameters::Converter
      include Surge::Internal::Type::RequestParameters

      def initialize: (?request_options: Surge::request_opts) -> void

      def to_hash: -> { request_options: Surge::RequestOptions }
    end
  end
end
