module Surge
  module Models
    type user_token_response = { token: String }

    class UserTokenResponse < Surge::Internal::Type::BaseModel
      attr_reader token: String?

      def token=: (String) -> String

      def initialize: (?token: String) -> void

      def to_hash: -> { token: String }
    end
  end
end
