module Surge
  module Models
    type verification =
      {
        id: String,
        attempt_count: Integer,
        phone_number: String,
        status: Surge::Models::Verification::status
      }

    class Verification < Surge::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor attempt_count: Integer

      attr_accessor phone_number: String

      attr_accessor status: Surge::Models::Verification::status

      def initialize: (
        id: String,
        attempt_count: Integer,
        phone_number: String,
        status: Surge::Models::Verification::status
      ) -> void

      def to_hash: -> {
        id: String,
        attempt_count: Integer,
        phone_number: String,
        status: Surge::Models::Verification::status
      }

      type status = :pending | :verified | :exhausted | :expired

      module Status
        extend Surge::Internal::Type::Enum

        PENDING: :pending
        VERIFIED: :verified
        EXHAUSTED: :exhausted
        EXPIRED: :expired

        def self?.values: -> ::Array[Surge::Models::Verification::status]
      end
    end
  end
end
