module Surge
  module Models
    type webhook_unwrap_params =
      {  } & Surge::Internal::Type::request_parameters

    class WebhookUnwrapParams < Surge::Internal::Type::BaseModel
      extend Surge::Internal::Type::RequestParameters::Converter
      include Surge::Internal::Type::RequestParameters

      def initialize: (?request_options: Surge::request_opts) -> void

      def to_hash: -> { request_options: Surge::RequestOptions }
    end
  end
end
