module SurgeAPI
  module Internal
    class Cursor[Elem]
      include SurgeAPI::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor pagination: Pagination

      def inspect: -> String

      type pagination = { next_cursor: String, previous_cursor: String }
      class Pagination < SurgeAPI::Internal::Type::BaseModel
        attr_reader next_cursor: String?

        def next_cursor=: (String) -> String

        attr_reader previous_cursor: String?

        def previous_cursor=: (String) -> String

        def initialize: (?next_cursor: String, ?previous_cursor: String) -> void

        def to_hash: -> { next_cursor: String, previous_cursor: String }
      end
    end
  end
end
