module SurgeAPI
  module Models
    type account_status =
      { capabilities: ::Hash[Symbol, SurgeAPI::AccountStatus::Capability] }

    class AccountStatus < SurgeAPI::Internal::Type::BaseModel
      attr_accessor capabilities: ::Hash[Symbol, SurgeAPI::AccountStatus::Capability]

      def initialize: (
        capabilities: ::Hash[Symbol, SurgeAPI::AccountStatus::Capability]
      ) -> void

      def to_hash: -> {
        capabilities: ::Hash[Symbol, SurgeAPI::AccountStatus::Capability]
      }

      type capability =
        {
          errors: ::Array[SurgeAPI::AccountStatus::Capability::Error],
          fields_needed: ::Array[String],
          status: SurgeAPI::Models::AccountStatus::Capability::status
        }

      class Capability < SurgeAPI::Internal::Type::BaseModel
        attr_accessor errors: ::Array[SurgeAPI::AccountStatus::Capability::Error]

        attr_accessor fields_needed: ::Array[String]

        attr_accessor status: SurgeAPI::Models::AccountStatus::Capability::status

        def initialize: (
          errors: ::Array[SurgeAPI::AccountStatus::Capability::Error],
          fields_needed: ::Array[String],
          status: SurgeAPI::Models::AccountStatus::Capability::status
        ) -> void

        def to_hash: -> {
          errors: ::Array[SurgeAPI::AccountStatus::Capability::Error],
          fields_needed: ::Array[String],
          status: SurgeAPI::Models::AccountStatus::Capability::status
        }

        type error = { field: String, message: String, type: String }

        class Error < SurgeAPI::Internal::Type::BaseModel
          attr_accessor field: String

          attr_accessor message: String

          attr_accessor type: String

          def initialize: (field: String, message: String, type: String) -> void

          def to_hash: -> { field: String, message: String, type: String }
        end

        type status = :error | :incomplete | :ready

        module Status
          extend SurgeAPI::Internal::Type::Enum

          ERROR: :error
          INCOMPLETE: :incomplete
          READY: :ready

          def self?.values: -> ::Array[SurgeAPI::Models::AccountStatus::Capability::status]
        end
      end
    end
  end
end
