module SurgeAPI
  module Models
    type attachment_get_file_params =
      { attachment_id: String } & SurgeAPI::Internal::Type::request_parameters

    class AttachmentGetFileParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_accessor attachment_id: String

      def initialize: (
        attachment_id: String,
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        attachment_id: String,
        request_options: SurgeAPI::RequestOptions
      }
    end
  end
end
