module SurgeAPI
  module Models
    type audience_create_response = { id: String, name: String }

    class AudienceCreateResponse < SurgeAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      def initialize: (id: String, name: String) -> void

      def to_hash: -> { id: String, name: String }
    end
  end
end
