module SurgeAPI
  module Models
    type blast_create_params =
      {
        attachments: ::Array[SurgeAPI::BlastCreateParams::Attachment],
        body: String?,
        contacts: ::Array[String],
        from: String,
        name: String,
        segments: ::Array[String],
        send_at: Time,
        to: ::Array[String]
      }
      & SurgeAPI::Internal::Type::request_parameters

    class BlastCreateParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_reader attachments: ::Array[SurgeAPI::BlastCreateParams::Attachment]?

      def attachments=: (
        ::Array[SurgeAPI::BlastCreateParams::Attachment]
      ) -> ::Array[SurgeAPI::BlastCreateParams::Attachment]

      attr_accessor body: String?

      attr_reader contacts: ::Array[String]?

      def contacts=: (::Array[String]) -> ::Array[String]

      attr_reader from: String?

      def from=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader segments: ::Array[String]?

      def segments=: (::Array[String]) -> ::Array[String]

      attr_reader send_at: Time?

      def send_at=: (Time) -> Time

      attr_reader to: ::Array[String]?

      def to=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?attachments: ::Array[SurgeAPI::BlastCreateParams::Attachment],
        ?body: String?,
        ?contacts: ::Array[String],
        ?from: String,
        ?name: String,
        ?segments: ::Array[String],
        ?send_at: Time,
        ?to: ::Array[String],
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        attachments: ::Array[SurgeAPI::BlastCreateParams::Attachment],
        body: String?,
        contacts: ::Array[String],
        from: String,
        name: String,
        segments: ::Array[String],
        send_at: Time,
        to: ::Array[String],
        request_options: SurgeAPI::RequestOptions
      }

      type attachment = { url: String }

      class Attachment < SurgeAPI::Internal::Type::BaseModel
        attr_accessor url: String

        def initialize: (url: String) -> void

        def to_hash: -> { url: String }
      end
    end
  end
end
