module SurgeAPI
  module Models
    type campaign_create_params =
      {  } & SurgeAPI::Internal::Type::request_parameters

    class CampaignCreateParams < SurgeAPI::Models::CampaignParams
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: SurgeAPI::request_opts) -> void

      def to_hash: -> { request_options: SurgeAPI::RequestOptions }
    end
  end
end
