module SurgeAPI
  module Models
    type contact_create_params =
      {
        account_id: String,
        phone_number: String,
        email: String,
        first_name: String,
        last_name: String,
        metadata: ::Hash[Symbol, String],
        outbound_disabled: bool
      }
      & SurgeAPI::Internal::Type::request_parameters

    class ContactCreateParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_accessor account_id: String

      attr_accessor phone_number: String

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader first_name: String?

      def first_name=: (String) -> String

      attr_reader last_name: String?

      def last_name=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader outbound_disabled: bool?

      def outbound_disabled=: (bool) -> bool

      def initialize: (
        account_id: String,
        phone_number: String,
        ?email: String,
        ?first_name: String,
        ?last_name: String,
        ?metadata: ::Hash[Symbol, String],
        ?outbound_disabled: bool,
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        account_id: String,
        phone_number: String,
        email: String,
        first_name: String,
        last_name: String,
        metadata: ::Hash[Symbol, String],
        outbound_disabled: bool,
        request_options: SurgeAPI::RequestOptions
      }
    end
  end
end
