module SurgeAPI
  module Models
    type link_followed_webhook_event =
      {
        account_id: String,
        data: SurgeAPI::LinkFollowedWebhookEvent::Data,
        timestamp: Time,
        type: :"link.followed"
      }

    class LinkFollowedWebhookEvent < SurgeAPI::Internal::Type::BaseModel
      attr_accessor account_id: String

      attr_accessor data: SurgeAPI::LinkFollowedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"link.followed"

      def initialize: (
        account_id: String,
        data: SurgeAPI::LinkFollowedWebhookEvent::Data,
        timestamp: Time,
        ?type: :"link.followed"
      ) -> void

      def to_hash: -> {
        account_id: String,
        data: SurgeAPI::LinkFollowedWebhookEvent::Data,
        timestamp: Time,
        type: :"link.followed"
      }

      type data = { id: String, message_id: String, url: String }

      class Data < SurgeAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor message_id: String

        attr_accessor url: String

        def initialize: (id: String, message_id: String, url: String) -> void

        def to_hash: -> { id: String, message_id: String, url: String }
      end
    end
  end
end
