module SurgeAPI
  module Models
    type message_received_webhook_event =
      {
        account_id: String,
        data: SurgeAPI::MessageReceivedWebhookEvent::Data,
        timestamp: Time,
        type: :"message.received"
      }

    class MessageReceivedWebhookEvent < SurgeAPI::Internal::Type::BaseModel
      attr_accessor account_id: String

      attr_accessor data: SurgeAPI::MessageReceivedWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: :"message.received"

      def initialize: (
        account_id: String,
        data: SurgeAPI::MessageReceivedWebhookEvent::Data,
        timestamp: Time,
        ?type: :"message.received"
      ) -> void

      def to_hash: -> {
        account_id: String,
        data: SurgeAPI::MessageReceivedWebhookEvent::Data,
        timestamp: Time,
        type: :"message.received"
      }

      type data =
        {
          id: String,
          body: String,
          conversation: SurgeAPI::MessageReceivedWebhookEvent::Data::Conversation,
          received_at: Time,
          attachments: ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]
        }

      class Data < SurgeAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor body: String

        attr_accessor conversation: SurgeAPI::MessageReceivedWebhookEvent::Data::Conversation

        attr_accessor received_at: Time

        attr_reader attachments: ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]?

        def attachments=: (
          ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]
        ) -> ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]

        def initialize: (
          id: String,
          body: String,
          conversation: SurgeAPI::MessageReceivedWebhookEvent::Data::Conversation,
          received_at: Time,
          ?attachments: ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]
        ) -> void

        def to_hash: -> {
          id: String,
          body: String,
          conversation: SurgeAPI::MessageReceivedWebhookEvent::Data::Conversation,
          received_at: Time,
          attachments: ::Array[SurgeAPI::MessageReceivedWebhookEvent::Data::Attachment]
        }

        type conversation =
          {
            id: String,
            contact: SurgeAPI::Contact,
            phone_number: SurgeAPI::PhoneNumber
          }

        class Conversation < SurgeAPI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor contact: SurgeAPI::Contact

          attr_accessor phone_number: SurgeAPI::PhoneNumber

          def initialize: (
            id: String,
            contact: SurgeAPI::Contact,
            phone_number: SurgeAPI::PhoneNumber
          ) -> void

          def to_hash: -> {
            id: String,
            contact: SurgeAPI::Contact,
            phone_number: SurgeAPI::PhoneNumber
          }
        end

        type attachment =
          {
            id: String,
            type: SurgeAPI::Models::MessageReceivedWebhookEvent::Data::Attachment::type_,
            url: String
          }

        class Attachment < SurgeAPI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor type: SurgeAPI::Models::MessageReceivedWebhookEvent::Data::Attachment::type_

          attr_accessor url: String

          def initialize: (
            id: String,
            type: SurgeAPI::Models::MessageReceivedWebhookEvent::Data::Attachment::type_,
            url: String
          ) -> void

          def to_hash: -> {
            id: String,
            type: SurgeAPI::Models::MessageReceivedWebhookEvent::Data::Attachment::type_,
            url: String
          }

          type type_ = :file | :image | :link | :video

          module Type
            extend SurgeAPI::Internal::Type::Enum

            FILE: :file
            IMAGE: :image
            LINK: :link
            VIDEO: :video

            def self?.values: -> ::Array[SurgeAPI::Models::MessageReceivedWebhookEvent::Data::Attachment::type_]
          end
        end
      end
    end
  end
end
