module SurgeAPI
  module Models
    type message_params =
      SurgeAPI::MessageParams::MessageParamsWithConversation
      | SurgeAPI::MessageParams::SimpleMessageParams

    module MessageParams
      extend SurgeAPI::Internal::Type::Union

      type message_params_with_conversation =
        {
          conversation: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation,
          attachments: ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment],
          body: String,
          metadata: ::Hash[Symbol, String],
          send_at: Time,
          settings: SurgeAPI::MessageParams::MessageParamsWithConversation::Settings
        }

      class MessageParamsWithConversation < SurgeAPI::Internal::Type::BaseModel
        attr_accessor conversation: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation

        attr_reader attachments: ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment]?

        def attachments=: (
          ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment]
        ) -> ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment]

        attr_reader body: String?

        def body=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader send_at: Time?

        def send_at=: (Time) -> Time

        attr_reader settings: SurgeAPI::MessageParams::MessageParamsWithConversation::Settings?

        def settings=: (
          SurgeAPI::MessageParams::MessageParamsWithConversation::Settings
        ) -> SurgeAPI::MessageParams::MessageParamsWithConversation::Settings

        def initialize: (
          conversation: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation,
          ?attachments: ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment],
          ?body: String,
          ?metadata: ::Hash[Symbol, String],
          ?send_at: Time,
          ?settings: SurgeAPI::MessageParams::MessageParamsWithConversation::Settings
        ) -> void

        def to_hash: -> {
          conversation: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation,
          attachments: ::Array[SurgeAPI::MessageParams::MessageParamsWithConversation::Attachment],
          body: String,
          metadata: ::Hash[Symbol, String],
          send_at: Time,
          settings: SurgeAPI::MessageParams::MessageParamsWithConversation::Settings
        }

        type conversation =
          {
            contact: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation::Contact,
            phone_number: String
          }

        class Conversation < SurgeAPI::Internal::Type::BaseModel
          attr_accessor contact: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation::Contact

          attr_reader phone_number: String?

          def phone_number=: (String) -> String

          def initialize: (
            contact: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation::Contact,
            ?phone_number: String
          ) -> void

          def to_hash: -> {
            contact: SurgeAPI::MessageParams::MessageParamsWithConversation::Conversation::Contact,
            phone_number: String
          }

          type contact =
            {
              phone_number: String,
              email: String,
              first_name: String,
              last_name: String,
              metadata: ::Hash[Symbol, String]
            }

          class Contact < SurgeAPI::Internal::Type::BaseModel
            attr_accessor phone_number: String

            attr_reader email: String?

            def email=: (String) -> String

            attr_reader first_name: String?

            def first_name=: (String) -> String

            attr_reader last_name: String?

            def last_name=: (String) -> String

            attr_reader metadata: ::Hash[Symbol, String]?

            def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            def initialize: (
              phone_number: String,
              ?email: String,
              ?first_name: String,
              ?last_name: String,
              ?metadata: ::Hash[Symbol, String]
            ) -> void

            def to_hash: -> {
              phone_number: String,
              email: String,
              first_name: String,
              last_name: String,
              metadata: ::Hash[Symbol, String]
            }
          end
        end

        type attachment = { url: String }

        class Attachment < SurgeAPI::Internal::Type::BaseModel
          attr_accessor url: String

          def initialize: (url: String) -> void

          def to_hash: -> { url: String }
        end

        type settings =
          {
            link_shortening: SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening
          }

        class Settings < SurgeAPI::Internal::Type::BaseModel
          attr_reader link_shortening: SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening?

          def link_shortening=: (
            SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening
          ) -> SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening

          def initialize: (
            ?link_shortening: SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening
          ) -> void

          def to_hash: -> {
            link_shortening: SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening
          }

          type link_shortening = :enabled | :disabled

          module LinkShortening
            extend SurgeAPI::Internal::Type::Enum

            ENABLED: :enabled
            DISABLED: :disabled

            def self?.values: -> ::Array[SurgeAPI::Models::MessageParams::MessageParamsWithConversation::Settings::link_shortening]
          end
        end
      end

      type simple_message_params =
        {
          to: String,
          attachments: ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment],
          body: String,
          from: String,
          metadata: ::Hash[Symbol, String],
          send_at: Time,
          settings: SurgeAPI::MessageParams::SimpleMessageParams::Settings
        }

      class SimpleMessageParams < SurgeAPI::Internal::Type::BaseModel
        attr_accessor to: String

        attr_reader attachments: ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment]?

        def attachments=: (
          ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment]
        ) -> ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment]

        attr_reader body: String?

        def body=: (String) -> String

        attr_reader from: String?

        def from=: (String) -> String

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader send_at: Time?

        def send_at=: (Time) -> Time

        attr_reader settings: SurgeAPI::MessageParams::SimpleMessageParams::Settings?

        def settings=: (
          SurgeAPI::MessageParams::SimpleMessageParams::Settings
        ) -> SurgeAPI::MessageParams::SimpleMessageParams::Settings

        def initialize: (
          to: String,
          ?attachments: ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment],
          ?body: String,
          ?from: String,
          ?metadata: ::Hash[Symbol, String],
          ?send_at: Time,
          ?settings: SurgeAPI::MessageParams::SimpleMessageParams::Settings
        ) -> void

        def to_hash: -> {
          to: String,
          attachments: ::Array[SurgeAPI::MessageParams::SimpleMessageParams::Attachment],
          body: String,
          from: String,
          metadata: ::Hash[Symbol, String],
          send_at: Time,
          settings: SurgeAPI::MessageParams::SimpleMessageParams::Settings
        }

        type attachment = { url: String }

        class Attachment < SurgeAPI::Internal::Type::BaseModel
          attr_accessor url: String

          def initialize: (url: String) -> void

          def to_hash: -> { url: String }
        end

        type settings =
          {
            link_shortening: SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening
          }

        class Settings < SurgeAPI::Internal::Type::BaseModel
          attr_reader link_shortening: SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening?

          def link_shortening=: (
            SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening
          ) -> SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening

          def initialize: (
            ?link_shortening: SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening
          ) -> void

          def to_hash: -> {
            link_shortening: SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening
          }

          type link_shortening = :enabled | :disabled

          module LinkShortening
            extend SurgeAPI::Internal::Type::Enum

            ENABLED: :enabled
            DISABLED: :disabled

            def self?.values: -> ::Array[SurgeAPI::Models::MessageParams::SimpleMessageParams::Settings::link_shortening]
          end
        end
      end

      def self?.variants: -> ::Array[SurgeAPI::Models::message_params]
    end
  end
end
