module SurgeAPI
  module Models
    type phone_number =
      {
        id: String,
        campaign: SurgeAPI::PhoneNumber::Campaign?,
        campaign_id: String?,
        name: String?,
        number: String,
        type: SurgeAPI::Models::PhoneNumber::type_
      }

    class PhoneNumber < SurgeAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor campaign: SurgeAPI::PhoneNumber::Campaign?

      attr_accessor campaign_id: String?

      attr_accessor name: String?

      attr_accessor number: String

      attr_accessor type: SurgeAPI::Models::PhoneNumber::type_

      def initialize: (
        id: String,
        campaign: SurgeAPI::PhoneNumber::Campaign?,
        campaign_id: String?,
        name: String?,
        number: String,
        type: SurgeAPI::Models::PhoneNumber::type_
      ) -> void

      def to_hash: -> {
        id: String,
        campaign: SurgeAPI::PhoneNumber::Campaign?,
        campaign_id: String?,
        name: String?,
        number: String,
        type: SurgeAPI::Models::PhoneNumber::type_
      }

      type campaign =
        {
          id: String,
          attachment_status: SurgeAPI::Models::PhoneNumber::Campaign::attachment_status
        }

      class Campaign < SurgeAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor attachment_status: SurgeAPI::Models::PhoneNumber::Campaign::attachment_status

        def initialize: (
          id: String,
          attachment_status: SurgeAPI::Models::PhoneNumber::Campaign::attachment_status
        ) -> void

        def to_hash: -> {
          id: String,
          attachment_status: SurgeAPI::Models::PhoneNumber::Campaign::attachment_status
        }

        type attachment_status =
          :attached | :attachment_pending | :detached | :detachment_pending

        module AttachmentStatus
          extend SurgeAPI::Internal::Type::Enum

          ATTACHED: :attached
          ATTACHMENT_PENDING: :attachment_pending
          DETACHED: :detached
          DETACHMENT_PENDING: :detachment_pending

          def self?.values: -> ::Array[SurgeAPI::Models::PhoneNumber::Campaign::attachment_status]
        end
      end

      type type_ = :local | :short_code | :toll_free

      module Type
        extend SurgeAPI::Internal::Type::Enum

        LOCAL: :local
        SHORT_CODE: :short_code
        TOLL_FREE: :toll_free

        def self?.values: -> ::Array[SurgeAPI::Models::PhoneNumber::type_]
      end
    end
  end
end
