module SurgeAPI
  module Models
    type recording_get_file_params =
      { recording_id: String } & SurgeAPI::Internal::Type::request_parameters

    class RecordingGetFileParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_accessor recording_id: String

      def initialize: (
        recording_id: String,
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        recording_id: String,
        request_options: SurgeAPI::RequestOptions
      }
    end
  end
end
