module SurgeAPI
  module Models
    type unwrap_webhook_event =
      SurgeAPI::CallEndedWebhookEvent
      | SurgeAPI::CampaignApprovedWebhookEvent
      | SurgeAPI::ContactOptedInWebhookEvent
      | SurgeAPI::ContactOptedOutWebhookEvent
      | SurgeAPI::ConversationCreatedWebhookEvent
      | SurgeAPI::LinkFollowedWebhookEvent
      | SurgeAPI::MessageDeliveredWebhookEvent
      | SurgeAPI::MessageFailedWebhookEvent
      | SurgeAPI::MessageReceivedWebhookEvent
      | SurgeAPI::MessageSentWebhookEvent
      | SurgeAPI::RecordingCompletedWebhookEvent
      | SurgeAPI::VoicemailReceivedWebhookEvent

    module UnwrapWebhookEvent
      extend SurgeAPI::Internal::Type::Union

      def self?.variants: -> ::Array[SurgeAPI::Models::unwrap_webhook_event]
    end
  end
end
