module SurgeAPI
  module Models
    type user_update_params =
      {
        first_name: String,
        last_name: String,
        metadata: ::Hash[Symbol, String],
        photo_url: String
      }
      & SurgeAPI::Internal::Type::request_parameters

    class UserUpdateParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_accessor first_name: String

      attr_reader last_name: String?

      def last_name=: (String) -> String

      attr_reader metadata: ::Hash[Symbol, String]?

      def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader photo_url: String?

      def photo_url=: (String) -> String

      def initialize: (
        first_name: String,
        ?last_name: String,
        ?metadata: ::Hash[Symbol, String],
        ?photo_url: String,
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        first_name: String,
        last_name: String,
        metadata: ::Hash[Symbol, String],
        photo_url: String,
        request_options: SurgeAPI::RequestOptions
      }
    end
  end
end
