module SurgeAPI
  module Models
    type verification_check_params =
      { id: String, code: String }
      & SurgeAPI::Internal::Type::request_parameters

    class VerificationCheckParams < SurgeAPI::Internal::Type::BaseModel
      extend SurgeAPI::Internal::Type::RequestParameters::Converter
      include SurgeAPI::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor code: String

      def initialize: (
        id: String,
        code: String,
        ?request_options: SurgeAPI::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        code: String,
        request_options: SurgeAPI::RequestOptions
      }
    end
  end
end
