module SurgeAPI
  module Resources
    class Campaigns
      def create: (
        String account_id,
        campaign_params: SurgeAPI::Models::CampaignParams,
        ?request_options: SurgeAPI::request_opts
      ) -> SurgeAPI::Campaign

      def initialize: (client: SurgeAPI::Client) -> void
    end
  end
end
