module SurgeAPI
  module Resources
    class Messages
      def create: (
        String account_id,
        params: SurgeAPI::Models::MessageCreateParams::params,
        ?request_options: SurgeAPI::request_opts
      ) -> SurgeAPI::Message

      def initialize: (client: SurgeAPI::Client) -> void
    end
  end
end
