module SurgeAPI
  module Resources
    class Messages
      def create: (
        String account_id,
        message_params: SurgeAPI::Models::MessageParams,
        ?request_options: SurgeAPI::request_opts
      ) -> SurgeAPI::Message

      def retrieve: (
        String id,
        ?request_options: SurgeAPI::request_opts
      ) -> SurgeAPI::Message

      def list: (
        String account_id,
        ?after: String,
        ?before: String,
        ?request_options: SurgeAPI::request_opts
      ) -> SurgeAPI::Internal::Cursor[SurgeAPI::Message]

      def initialize: (client: SurgeAPI::Client) -> void
    end
  end
end
