module SurgeAPI
  module Resources
    class Webhooks
      def unwrap: (
        String payload
      ) -> (SurgeAPI::CallEndedWebhookEvent
      | SurgeAPI::CampaignApprovedWebhookEvent
      | SurgeAPI::ContactOptedInWebhookEvent
      | SurgeAPI::ContactOptedOutWebhookEvent
      | SurgeAPI::ConversationCreatedWebhookEvent
      | SurgeAPI::MessageDeliveredWebhookEvent
      | SurgeAPI::MessageFailedWebhookEvent
      | SurgeAPI::MessageReceivedWebhookEvent
      | SurgeAPI::MessageSentWebhookEvent)

      def initialize: (client: SurgeAPI::Client) -> void
    end
  end
end
